# Generated by Django 6.0.6 on 2026-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='nilai_akhir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='status_hadir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siswa',
            name='tgl_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='umur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='siswa',
            table=None,
        ),
    ]
